In [642]:
#importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [643]:
#Reading the csv file
data=pd.read_csv('cpdata.csv')
# print(data.head(1))

In [644]:
#Creating dummy variable for target i.e label
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.drop('label', axis=1,inplace=True)
print('The data present in one row of the dataset is')
print(data.head(2))
column_headers = list(data.columns.values)
print("The Column Header :", column_headers)
train=data.iloc[:, 0:3].values
test=data.iloc[: ,3:].values

The data present in one row of the dataset is
   temperature   humidity    rainfall  Black gram  Chickpea  Coconut  Coffee  \
0    20.879744  82.002744  202.935536           0         0        0       0   
1    21.770462  80.319644  226.655537           0         0        0       0   

   Cotton  Ground Nut  Jute  ...  maize  mango  millet  muskmelon  orange  \
0       0           0     0  ...      0      0       0          0       0   
1       0           0     0  ...      0      0       0          0       0   

   papaya  pomegranate  rice  watermelon  wheat  
0       0            0     1           0      0  
1       0            0     1           0      0  

[2 rows x 33 columns]
The Column Header : ['temperature', 'humidity', 'rainfall', 'Black gram', 'Chickpea', 'Coconut', 'Coffee', 'Cotton', 'Ground Nut', 'Jute', 'Kidney Beans', 'Lentil', 'Moth Beans', 'Mung Bean', 'Peas', 'Pigeon Peas', 'Rubber', 'Sugarcane', 'Tea', 'Tobacco', 'apple', 'banana', 'grapes', 'maize', 'mango', 'mill

In [645]:
#Dividing the data into training and test set
X_train,X_test,y_train,y_test=train_test_split(train,test,test_size=0.1)
print(X_train[0])
print(X_test[0])
print(y_train[0])
print(y_test[0])

[19.2582557  14.2804191  65.78042032]
[ 23.12808226  92.68328358 109.3930157 ]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [646]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [647]:
#Importing Decision Tree classifier
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()

In [648]:
#Fitting the classifier into training set
clf.fit(X_train,y_train)
pred=clf.predict(X_test)
print(X_test[0])
print(pred[0])

[ 23.12808226  92.68328358 109.3930157 ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [649]:
from sklearn.metrics import accuracy_score
# Finding the accuracy of the model
a=accuracy_score(y_test,pred)
print("The accuracy of this model is: ", a*100)

The accuracy of this model is:  84.19354838709677


In [650]:
# #Using firebase to import data to be tested
# from firebase import firebase
# firebase =firebase.FirebaseApplication('https://cropit-eb156.firebaseio.com/')
# tp=firebase.get('/Realtime',None)

In [651]:
atemp = 25.2
ah = 76
shum = 0
pH = 0
rain = 60.32

In [652]:
l=[]
l.append(atemp)
l.append(ah)
#l.append(pH)
l.append(rain)
predictcrop=[l]
print(l)

[25.2, 76, 60.32]


In [653]:
# Putting the names of crop in a single list
crops=['Black gram', 'Chickpea', 'Coconut', 'Coffee', 'Cotton', 'Ground Nut', 'Jute', 'Kidney Beans', 'Lentil', 'Moth Beans', 'Mung Bean', 'Peas', 'Pigeon Peas', 'Rubber', 'Sugarcane', 'Tea', 'Tobacco', 'apple', 'banana', 'grapes', 'maize', 'mango', 'millet', 'muskmelon', 'orange', 'papaya', 'pomegranate', 'rice', 'watermelon', 'wheat']
print(len(crops))

30


In [654]:
#Predicting the crop
predictions = clf.predict(predictcrop)
count = 0
for i in range(0,len(predictions[0])):
    if(predictions[0][i] == 1):
        print(i)
        print('The predicted crop is %s'%crops[i])
        count = 1
        break;
if(count == 0):
    print("fail")

4
The predicted crop is Cotton


In [655]:
# #Sending the predicted crop to database
# cp=firebase.put('/croppredicted','crop',c)